apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nzbget
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: nzbget.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nzbget
          servicePort: 6789
  